const fs = require('fs');

let content = fs.readFileSync('app/page.js', 'utf8');

const searchTransObj = `          const searchTrans = {
            title: { 'en-US': 'Search & Add Items', 'ja-JP': 'アイテムを検索して追加', 'zh-Hans': '搜索并添加物品', 'zh-Hant': '搜尋並新增物品', 'ko-KR': '아이템 검색 및 추가', 'ru-RU': 'Поиск и добавление предметов', 'es-ES': 'Buscar y agregar artículos', 'fr-FR': 'Rechercher et ajouter des objets', 'de-DE': 'Suchen & Gegenstände hinzufügen', 'pt-BR': 'Buscar e Adicionar Itens', 'tr-TR': 'Öğe Ara ve Ekle', 'vi-VN': 'Tìm kiếm & Thêm Vật phẩm', 'id-ID': 'Cari & Tambah Item', 'th-TH': 'ค้นหาและเพิ่มไอเทม', 'pl-PL': 'Szukaj i dodawaj przedmioty', 'uk-UA': 'Пошук і додавання предметів' },
            placeholder: { 'en-US': 'Search by name...', 'ja-JP': '名前で検索...', 'zh-Hans': '按名称搜索...', 'zh-Hant': '按名稱搜尋...', 'ko-KR': '이름으로 검색...', 'ru-RU': 'Поиск по имени...', 'es-ES': 'Buscar por nombre...', 'fr-FR': 'Rechercher par nom...', 'de-DE': 'Nach Name suchen...', 'pt-BR': 'Buscar por nome...', 'tr-TR': 'İsme göre ara...', 'vi-VN': 'Tìm kiếm theo tên...', 'id-ID': 'Cari berdasarkan nama...', 'th-TH': 'ค้นหาตามชื่อ...', 'pl-PL': 'Szukaj po nazwie...', 'uk-UA': 'Пошук за назвою...' },
            all: { 'en-US': 'All Categories', 'ja-JP': 'すべての種類', 'zh-Hans': '所有类别', 'zh-Hant': '所有類別', 'ko-KR': '모든 카테고리', 'ru-RU': 'Все категории', 'es-ES': 'Todas las categorías', 'fr-FR': 'Toutes les catégories', 'de-DE': 'Alle Kategorien', 'pt-BR': 'Todas as Categorias', 'tr-TR': 'Tüm Kategoriler', 'vi-VN': 'Tất cả danh mục', 'id-ID': 'Semua Kategori', 'th-TH': 'หมวดหมู่ทั้งหมด', 'pl-PL': 'Wszystkie Kategorie', 'uk-UA': 'Всі категорії' },
            gear: { 'en-US': 'Gear', 'ja-JP': '装備', 'zh-Hans': '装备', 'zh-Hant': '裝備', 'ko-KR': '장비', 'ru-RU': 'Снаряжение', 'es-ES': 'Equipamiento', 'fr-FR': 'Équipement', 'de-DE': 'Ausrüstung', 'pt-BR': 'Equipamento', 'tr-TR': 'Ekipman', 'vi-VN': 'Trang bị', 'id-ID': 'Perlengkapan', 'th-TH': 'อุปกรณ์', 'pl-PL': 'Ekwipunek', 'uk-UA': 'Спорядження' },
            allClasses: { 'en-US': 'All Classes', 'ja-JP': 'すべての部位', 'zh-Hans': '所有部位', 'zh-Hant': '所有部位', 'ko-KR': '모든 부위', 'ru-RU': 'Все типы', 'es-ES': 'Todas las clases', 'fr-FR': 'Toutes les classes', 'de-DE': 'Alle Klassen', 'pt-BR': 'Todas as Classes', 'tr-TR': 'Tüm Sınıflar', 'vi-VN': 'Tất cả các lớp', 'id-ID': 'Semua Kelas', 'th-TH': 'ทุกคลาส', 'pl-PL': 'Wszystkie Klasy', 'uk-UA': 'Усі класи' },
            allRarities: { 'en-US': 'All Rarities', 'ja-JP': 'すべての等級', 'zh-Hans': '所有稀有度', 'zh-Hant': '所有稀有度', 'ko-KR': '모든 등급', 'ru-RU': 'Все редкости', 'es-ES': 'Todas las rarezas', 'fr-FR': 'Toutes les raretés', 'de-DE': 'Alle Seltenheiten', 'pt-BR': 'Todas as Raridades', 'tr-TR': 'Tüm Nadirlikler', 'vi-VN': 'Tất cả độ hiếm', 'id-ID': 'Semua Kelangkaan', 'th-TH': 'ความหายากทั้งหมด', 'pl-PL': 'Wszystkie Rzadkości', 'uk-UA': 'Усі рідкості' },
            levelPlaceholder: { 'en-US': 'Lv', 'ja-JP': 'Lv', 'zh-Hans': '等级', 'zh-Hant': '等級', 'ko-KR': '레벨', 'ru-RU': 'Ур', 'es-ES': 'Niv', 'fr-FR': 'Niv', 'de-DE': 'Stufe', 'pt-BR': 'Nív', 'tr-TR': 'Svy', 'vi-VN': 'Cấp', 'id-ID': 'Lv', 'th-TH': 'เลเวล', 'pl-PL': 'Poz', 'uk-UA': 'Рів' },
            sword: { 'en-US': 'Sword', 'ja-JP': '剣', 'zh-Hans': '剑', 'zh-Hant': '劍', 'ko-KR': '검', 'ru-RU': 'Меч', 'es-ES': 'Espada', 'fr-FR': 'Épée', 'de-DE': 'Schwert', 'pt-BR': 'Espada', 'tr-TR': 'Kılıç', 'vi-VN': 'Kiếm', 'id-ID': 'Pedang', 'th-TH': 'ดาบ', 'pl-PL': 'Miecz', 'uk-UA': 'Меч' },
            bow: { 'en-US': 'Bow', 'ja-JP': '弓', 'zh-Hans': '弓', 'zh-Hant': '弓', 'ko-KR': '활', 'ru-RU': 'Лук', 'es-ES': 'Arco', 'fr-FR': 'Arc', 'de-DE': 'Bogen', 'pt-BR': 'Arco', 'tr-TR': 'Yay', 'vi-VN': 'Cung', 'id-ID': 'Busur', 'th-TH': 'ธนู', 'pl-PL': 'Łuk', 'uk-UA': 'Лук' },
            staff: { 'en-US': 'Staff', 'ja-JP': '杖', 'zh-Hans': '法杖', 'zh-Hant': '法杖', 'ko-KR': '지팡이', 'ru-RU': 'Посох', 'es-ES': 'Bastón', 'fr-FR': 'Bâton', 'de-DE': 'Stab', 'pt-BR': 'Cajado', 'tr-TR': 'Asa', 'vi-VN': 'Gậy', 'id-ID': 'Tongkat', 'th-TH': 'ไม้เท้า', 'pl-PL': 'Kostur', 'uk-UA': 'Посох' },
            scepter: { 'en-US': 'Scepter', 'ja-JP': '王笏', 'zh-Hans': '权杖', 'zh-Hant': '權杖', 'ko-KR': '홀', 'ru-RU': 'Скипетр', 'es-ES': 'Cetro', 'fr-FR': 'Sceptre', 'de-DE': 'Zepter', 'pt-BR': 'Cetro', 'tr-TR': 'Asa', 'vi-VN': 'Quyền trượng', 'id-ID': 'Tongkat Kerajaan', 'th-TH': 'คทา', 'pl-PL': 'Berło', 'uk-UA': 'Скіпетр' },
            crossbow: { 'en-US': 'Crossbow', 'ja-JP': 'クロスボウ', 'zh-Hans': '弩', 'zh-Hant': '弩', 'ko-KR': '석궁', 'ru-RU': 'Арбалет', 'es-ES': 'Ballesta', 'fr-FR': 'Arbalète', 'de-DE': 'Armbrust', 'pt-BR': 'Besta', 'tr-TR': 'Arbalet', 'vi-VN': 'Nỏ', 'id-ID': 'Busur Silang', 'th-TH': 'หน้าไม้', 'pl-PL': 'Kusza', 'uk-UA': 'Арбалет' },
            axe: { 'en-US': 'Axe', 'ja-JP': '斧', 'zh-Hans': '斧头', 'zh-Hant': '斧頭', 'ko-KR': '도끼', 'ru-RU': 'Топор', 'es-ES': 'Hacha', 'fr-FR': 'Hache', 'de-DE': 'Axt', 'pt-BR': 'Machado', 'tr-TR': 'Balt', 'vi-VN': 'Rìu', 'id-ID': 'Kapak', 'th-TH': 'ขวาน', 'pl-PL': 'Topór', 'uk-UA': 'Сокира' },
            shield: { 'en-US': 'Shield', 'ja-JP': '盾', 'zh-Hans': '盾牌', 'zh-Hant': '盾牌', 'ko-KR': '방패', 'ru-RU': 'Щит', 'es-ES': 'Escudo', 'fr-FR': 'Bouclier', 'de-DE': 'Schild', 'pt-BR': 'Escudo', 'tr-TR': 'Kalkan', 'vi-VN': 'Khiên', 'id-ID': 'Perisai', 'th-TH': 'โล่', 'pl-PL': 'Tarcza', 'uk-UA': 'Щит' },
            arrow: { 'en-US': 'Arrow', 'ja-JP': '矢', 'zh-Hans': '箭', 'zh-Hant': '箭', 'ko-KR': '화살', 'ru-RU': 'Стрела', 'es-ES': 'Flecha', 'fr-FR': 'Flèche', 'de-DE': 'Pfeil', 'pt-BR': 'Flecha', 'tr-TR': 'Ok', 'vi-VN': 'Mũi tên', 'id-ID': 'Anak Panah', 'th-TH': 'ลูกศร', 'pl-PL': 'Strzała', 'uk-UA': 'Стріла' },
            orb: { 'en-US': 'Orb', 'ja-JP': 'オーブ', 'zh-Hans': '宝珠', 'zh-Hant': '寶珠', 'ko-KR': '오브', 'ru-RU': 'Сфера', 'es-ES': 'Orbe', 'fr-FR': 'Orbe', 'de-DE': 'Kugel', 'pt-BR': 'Orbe', 'tr-TR': 'Küre', 'vi-VN': 'Ngọc', 'id-ID': 'Orb', 'th-TH': 'ลูกแก้ว', 'pl-PL': 'Kula', 'uk-UA': 'Сфера' },
            tome: { 'en-US': 'Tome', 'ja-JP': '魔導書', 'zh-Hans': '法典', 'zh-Hant': '法典', 'ko-KR': '마도서', 'ru-RU': 'Фолиант', 'es-ES': 'Tomo', 'fr-FR': 'Tome', 'de-DE': 'Foliant', 'pt-BR': 'Tomo', 'tr-TR': 'Cilt', 'vi-VN': 'Sách phép', 'id-ID': 'Buku Sihir', 'th-TH': 'ตำรา', 'pl-PL': 'Księga', 'uk-UA': 'Том' },
            bolt: { 'en-US': 'Bolt', 'ja-JP': 'ボルト', 'zh-Hans': '弩箭', 'zh-Hant': '弩箭', 'ko-KR': '볼트', 'ru-RU': 'Болт', 'es-ES': 'Virote', 'fr-FR': 'Carreau', 'de-DE': 'Bolzen', 'pt-BR': 'Dardo', 'tr-TR': 'Civata', 'vi-VN': 'Bu lông', 'id-ID': 'Baut', 'th-TH': 'ลูกดอกไม้กางเขน', 'pl-PL': 'Bełt', 'uk-UA': 'Болт' },
            hatchet: { 'en-US': 'Hatchet', 'ja-JP': '手斧', 'zh-Hans': '短斧', 'zh-Hant': '短斧', 'ko-KR': '손도끼', 'ru-RU': 'Топорик', 'es-ES': 'Hachuela', 'fr-FR': 'Hachette', 'de-DE': 'Beil', 'pt-BR': 'Machadinha', 'tr-TR': 'Küçük Balta', 'vi-VN': 'Rìu nhỏ', 'id-ID': 'Kapak Kecil', 'th-TH': 'ขวานสั้น', 'pl-PL': 'Toporek', 'uk-UA': 'Топірець' },
            helmet: { 'en-US': 'Helmet', 'ja-JP': '兜', 'zh-Hans': '头盔', 'zh-Hant': '頭盔', 'ko-KR': '투구', 'ru-RU': 'Шлем', 'es-ES': 'Casco', 'fr-FR': 'Casque', 'de-DE': 'Helm', 'pt-BR': 'Capacete', 'tr-TR': 'Kask', 'vi-VN': 'Mũ bảo hiểm', 'id-ID': 'Helm', 'th-TH': 'หมวกเกราะ', 'pl-PL': 'Hełm', 'uk-UA': 'Шолом' },
            armor: { 'en-US': 'Armor', 'ja-JP': '鎧', 'zh-Hans': '盔甲', 'zh-Hant': '盔甲', 'ko-KR': '갑옷', 'ru-RU': 'Броня', 'es-ES': 'Armadura', 'fr-FR': 'Armure', 'de-DE': 'Rüstung', 'pt-BR': 'Armadura', 'tr-TR': 'Zırh', 'vi-VN': 'Áo giáp', 'id-ID': 'Baju Besi', 'th-TH': 'เสื้อเกราะ', 'pl-PL': 'Zbroja', 'uk-UA': 'Броня' },
            gloves: { 'en-US': 'Gloves', 'ja-JP': '手袋', 'zh-Hans': '手套', 'zh-Hant': '手套', 'ko-KR': '장갑', 'ru-RU': 'Перчатки', 'es-ES': 'Guantes', 'fr-FR': 'Gants', 'de-DE': 'Handschuhe', 'pt-BR': 'Luvas', 'tr-TR': 'Eldiven', 'vi-VN': 'Găng tay', 'id-ID': 'Sarung Tangan', 'th-TH': 'ถุงมือ', 'pl-PL': 'Rękawice', 'uk-UA': 'Рукавички' },
            boots: { 'en-US': 'Boots', 'ja-JP': '靴', 'zh-Hans': '靴子', 'zh-Hant': '靴子', 'ko-KR': '장화', 'ru-RU': 'Ботинки', 'es-ES': 'Botas', 'fr-FR': 'Bottes', 'de-DE': 'Stiefel', 'pt-BR': 'Botas', 'tr-TR': 'Çizme', 'vi-VN': 'Giày', 'id-ID': 'Sepatu Bot', 'th-TH': 'รองเท้าบูท', 'pl-PL': 'Buty', 'uk-UA': 'Чоботи' },
            amulet: { 'en-US': 'Amulet', 'ja-JP': '首飾り', 'zh-Hans': '护身符', 'zh-Hant': '護身符', 'ko-KR': '목걸이', 'ru-RU': 'Амулет', 'es-ES': 'Amuleto', 'fr-FR': 'Amulette', 'de-DE': 'Amulett', 'pt-BR': 'Amuleto', 'tr-TR': 'Muska', 'vi-VN': 'Bùa hộ mệnh', 'id-ID': 'Jimat', 'th-TH': 'เครื่องราง', 'pl-PL': 'Amulet', 'uk-UA': 'Амулет' },
            earing: { 'en-US': 'Earing', 'ja-JP': '耳飾り', 'zh-Hans': '耳环', 'zh-Hant': '耳環', 'ko-KR': '귀걸이', 'ru-RU': 'Серьга', 'es-ES': 'Pendiente', 'fr-FR': 'Boucle d\'oreille', 'de-DE': 'Ohrring', 'pt-BR': 'Brinco', 'tr-TR': 'Küpe', 'vi-VN': 'Bông tai', 'id-ID': 'Anting-anting', 'th-TH': 'ต่างหู', 'pl-PL': 'Kolczyk', 'uk-UA': 'Сережка' },
            ring: { 'en-US': 'Ring', 'ja-JP': '指輪', 'zh-Hans': '戒指', 'zh-Hant': '戒指', 'ko-KR': '반지', 'ru-RU': 'Кольцо', 'es-ES': 'Anillo', 'fr-FR': 'Anneau', 'de-DE': 'Ring', 'pt-BR': 'Anel', 'tr-TR': 'Yüzük', 'vi-VN': 'Nhẫn', 'id-ID': 'Cincin', 'th-TH': 'แหวน', 'pl-PL': 'Pierścień', 'uk-UA': 'Кільце' }
          };`;

content = content.replace(/const searchTrans = \{[\s\S]*?\n          \};/, searchTransObj);
fs.writeFileSync('app/page.js', content);
console.log('Updated searchTrans');
